/**
 * Deterministic Bundled Fallback Restaurant Dataset for TripResQ
 *
 * Provides instant, zero-latency, network-independent restaurant discovery for demo reliability.
 * Uses verified local image assets from /dining/ and matches real travel destinations.
 */

export const FALLBACK_RESTAURANTS = {
  pune: [
    {
      id: 'pune-fb-1',
      name: 'Shabree Restaurant',
      type: 'restaurant',
      cuisine: ['Maharashtrian', 'Thali', 'Local Specialties'],
      distanceKm: 0.4,
      address: '1199/1A FC Road, Deccan Gymkhana, Pune',
      openingHours: '11:30-23:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 23:00' },
      vegetarian: true,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 20 2553 1199',
      website: 'https://shabreerestaurant.com',
      rating: 4.7,
      avgCost: 750,
      imageUrl: '/dining/indian.jpg',
      image: '/dining/indian.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'pune-fb-2',
      name: 'German Bakery Café',
      type: 'cafe',
      cuisine: ['Bakery', 'Continental', 'Coffee', 'Desserts'],
      distanceKm: 1.1,
      address: '292 North Main Road, Koregaon Park, Pune',
      openingHours: '24/7',
      openStatus: { isOpen: true, statusText: 'Open 24/7' },
      vegetarian: false,
      vegan: true,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'yes',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 20 2615 6127',
      website: 'https://germanbakerypune.in',
      rating: 4.5,
      avgCost: 650,
      imageUrl: '/dining/bakery.jpg',
      image: '/dining/bakery.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'pune-fb-3',
      name: 'Vaishali Restaurant',
      type: 'restaurant',
      cuisine: ['South Indian', 'Dosa', 'Filter Coffee', 'Pure Veg'],
      distanceKm: 1.8,
      address: '1218/1 FC Road, Shivajinagar, Pune',
      openingHours: '07:00-23:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 23:00' },
      vegetarian: true,
      vegan: true,
      takeaway: 'yes',
      delivery: 'no',
      outdoorSeating: 'yes',
      wheelchair: 'limited',
      internetAccess: 'no',
      phone: '+91 20 2553 1244',
      website: null,
      rating: 4.8,
      avgCost: 400,
      imageUrl: '/dining/south-indian.jpg',
      image: '/dining/south-indian.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'pune-fb-4',
      name: 'Blue Nile Persian & Biryani Hub',
      type: 'restaurant',
      cuisine: ['Biryani', 'Mughlai', 'Tandoori', 'North Indian'],
      distanceKm: 2.2,
      address: '4 Bund Garden Road, Camp, Pune',
      openingHours: '11:30-23:30',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 23:30' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 20 2612 5238',
      website: null,
      rating: 4.4,
      avgCost: 900,
      imageUrl: '/dining/indian-2.jpg',
      image: '/dining/indian-2.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'pune-fb-5',
      name: 'Vohuman Café',
      type: 'cafe',
      cuisine: ['Irani Chai', 'Bun Maska', 'Breakfast', 'Fast Food'],
      distanceKm: 2.6,
      address: 'Near Pune Railway Station, Sassoon Road, Pune',
      openingHours: '06:00-19:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 19:00' },
      vegetarian: true,
      vegan: false,
      takeaway: 'yes',
      delivery: 'no',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'no',
      phone: '+91 20 2616 2707',
      website: null,
      rating: 4.6,
      avgCost: 250,
      imageUrl: '/dining/cafe.jpg',
      image: '/dining/cafe.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'pune-fb-6',
      name: 'Le Plaisir Patisserie & Bistro',
      type: 'restaurant',
      cuisine: ['European', 'Italian', 'Desserts', 'Salads'],
      distanceKm: 2.9,
      address: 'Prabhat Road, Erandwane, Pune',
      openingHours: '09:00-22:30',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 22:30' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'yes',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 85509 95865',
      website: null,
      rating: 4.9,
      avgCost: 1100,
      imageUrl: '/dining/pizza.jpg',
      image: '/dining/pizza.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    }
  ],

  goa: [
    {
      id: 'goa-fb-1',
      name: "Fisherman's Wharf",
      type: 'restaurant',
      cuisine: ['Goan Seafood', 'Prawn Balchão', 'Fish Curry', 'Local Specialties'],
      distanceKm: 0.6,
      address: 'At The Riverside, Salcette, Cavelossim, Goa',
      openingHours: '12:00-23:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 23:00' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'yes',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 832 287 1317',
      website: 'https://thefishermanswharf.in',
      rating: 4.8,
      avgCost: 1200,
      imageUrl: '/dining/restaurant.jpg',
      image: '/dining/restaurant.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'goa-fb-2',
      name: 'Gunpowder',
      type: 'restaurant',
      cuisine: ['South Indian', 'Kerala Curry', 'Appam', 'Local Specialties'],
      distanceKm: 1.3,
      address: 'Anjuna Mapusa Road, Saunto Vaddo, Assagao, Goa',
      openingHours: '12:00-23:30',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 23:30' },
      vegetarian: true,
      vegan: true,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'yes',
      wheelchair: 'limited',
      internetAccess: 'wifi',
      phone: '+91 832 226 8083',
      website: null,
      rating: 4.6,
      avgCost: 950,
      imageUrl: '/dining/south-indian-2.jpg',
      image: '/dining/south-indian-2.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'goa-fb-3',
      name: 'Baba Au Rhum',
      type: 'cafe',
      cuisine: ['Bakery', 'Artisan Coffee', 'Pizza', 'French Breakfast'],
      distanceKm: 0.8,
      address: 'Sim Vaddo, Anjuna, Goa',
      openingHours: '24/7',
      openStatus: { isOpen: true, statusText: 'Open 24/7' },
      vegetarian: false,
      vegan: true,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'yes',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 98228 66366',
      website: 'https://babaaurhum.com',
      rating: 4.7,
      avgCost: 800,
      imageUrl: '/dining/cafe-2.jpg',
      image: '/dining/cafe-2.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'goa-fb-4',
      name: 'Vinayak Family Restaurant',
      type: 'restaurant',
      cuisine: ['Pure Veg Thali', 'Konkani', 'Vegetarian', 'Fast Delivery'],
      distanceKm: 2.0,
      address: 'Camurlim Road, Assagao, Goa',
      openingHours: '12:00-15:30, 19:00-22:30',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 22:30' },
      vegetarian: true,
      vegan: true,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'no',
      phone: '+91 95455 33022',
      website: null,
      rating: 4.4,
      avgCost: 500,
      imageUrl: '/dining/vegetarian.jpg',
      image: '/dining/vegetarian.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'goa-fb-5',
      name: 'Thalassa Greek Taverna',
      type: 'restaurant',
      cuisine: ['Greek', 'Mediterranean', 'Seafood', 'Sunset Cocktails'],
      distanceKm: 3.5,
      address: 'Vaddy, Siolim, Goa',
      openingHours: '09:00-01:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 01:00' },
      vegetarian: false,
      vegan: false,
      takeaway: 'no',
      delivery: 'no',
      outdoorSeating: 'yes',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 98500 33537',
      website: 'https://thalassagao.com',
      rating: 4.9,
      avgCost: 2200,
      imageUrl: '/dining/restaurant-2.jpg',
      image: '/dining/restaurant-2.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'goa-fb-6',
      name: "Martin's Corner",
      type: 'restaurant',
      cuisine: ['Goan Heritage Seafood', 'Crab Xec Xec', 'Tandoor'],
      distanceKm: 4.2,
      address: 'Binwaddo, Betalbatim, Goa',
      openingHours: '11:00-23:30',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 23:30' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'yes',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 832 288 0413',
      website: 'https://martinscornergoa.com',
      rating: 4.8,
      avgCost: 1400,
      imageUrl: '/dining/indian-3.jpg',
      image: '/dining/indian-3.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    }
  ],

  mumbai: [
    {
      id: 'mum-fb-1',
      name: 'Britannia & Co. Restaurant',
      type: 'restaurant',
      cuisine: ['Parsi', 'Berry Pulao', 'Sali Boti', 'Local Specialties'],
      distanceKm: 0.5,
      address: 'Wakefield House, 11 Sprott Road, Ballard Estate, Fort, Mumbai',
      openingHours: '11:30-16:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 16:00' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'limited',
      internetAccess: 'no',
      phone: '+91 22 2261 5264',
      website: null,
      rating: 4.6,
      avgCost: 1100,
      imageUrl: '/dining/indian.jpg',
      image: '/dining/indian.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'mum-fb-2',
      name: 'Sukh Sagar Chowpatty',
      type: 'fast_food',
      cuisine: ['Pav Bhaji', 'Chaat', 'Pure Veg', 'Fresh Juices'],
      distanceKm: 0.8,
      address: 'Sardar Vallabhbhai Patel Road, Chowpatty, Mumbai',
      openingHours: '24/7',
      openStatus: { isOpen: true, statusText: 'Open 24/7' },
      vegetarian: true,
      vegan: true,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'no',
      phone: '+91 22 2367 0244',
      website: null,
      rating: 4.4,
      avgCost: 450,
      imageUrl: '/dining/fast-food.jpg',
      image: '/dining/fast-food.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'mum-fb-3',
      name: 'Bastian Bandra',
      type: 'restaurant',
      cuisine: ['Seafood', 'Continental', 'Asian', 'Cocktails'],
      distanceKm: 2.8,
      address: 'Linking Road, Bandra West, Mumbai',
      openingHours: '12:00-01:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 01:00' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'yes',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 22 5033 3555',
      website: 'https://bastianhospitality.com',
      rating: 4.8,
      avgCost: 2600,
      imageUrl: '/dining/restaurant.jpg',
      image: '/dining/restaurant.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'mum-fb-4',
      name: 'Kyani & Co. Bakery & Café',
      type: 'cafe',
      cuisine: ['Irani Bakery', 'Keema Pav', 'Mawa Cake', 'Filter Tea'],
      distanceKm: 1.2,
      address: 'Jermahal Estate, 657 JSS Road, Dhobi Talao, Mumbai',
      openingHours: '07:00-20:45',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 20:45' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'no',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'no',
      phone: '+91 22 2201 1492',
      website: null,
      rating: 4.5,
      avgCost: 350,
      imageUrl: '/dining/cafe-3.jpg',
      image: '/dining/cafe-3.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'mum-fb-5',
      name: 'Mahesh Lunch Home',
      type: 'restaurant',
      cuisine: ['Mangalorean Seafood', 'Butter Garlic Crab', 'Neer Dosa'],
      distanceKm: 1.7,
      address: '8-B Cawasji Patel Street, Fort, Mumbai',
      openingHours: '12:00-15:30, 19:00-23:30',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 23:30' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 22 2287 0938',
      website: 'https://maheshlunchhome.com',
      rating: 4.7,
      avgCost: 1500,
      imageUrl: '/dining/south-indian.jpg',
      image: '/dining/south-indian.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'mum-fb-6',
      name: 'Pizza By The Bay',
      type: 'restaurant',
      cuisine: ['Pizza', 'Italian', 'Pasta', 'Sea Facing'],
      distanceKm: 2.1,
      address: 'Marine Drive, Churchgate, Mumbai',
      openingHours: '07:00-00:30',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 00:30' },
      vegetarian: false,
      vegan: true,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'yes',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 22 2285 6115',
      website: 'https://pizzabythebay.in',
      rating: 4.6,
      avgCost: 1600,
      imageUrl: '/dining/pizza-2.jpg',
      image: '/dining/pizza-2.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    }
  ],

  delhi: [
    {
      id: 'del-fb-1',
      name: "Karim's Jama Masjid",
      type: 'restaurant',
      cuisine: ['Mughlai', 'Mutton Korma', 'Kebabs', 'Local Specialties'],
      distanceKm: 0.4,
      address: '16 Gali Kababian, Jama Masjid, Old Delhi',
      openingHours: '09:00-01:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 01:00' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'limited',
      internetAccess: 'no',
      phone: '+91 11 2326 9880',
      website: 'https://karimhoteldelhi.com',
      rating: 4.7,
      avgCost: 950,
      imageUrl: '/dining/indian-2.jpg',
      image: '/dining/indian-2.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'del-fb-2',
      name: 'Saravana Bhavan Connaught Place',
      type: 'restaurant',
      cuisine: ['South Indian', 'Ghee Roast Dosa', 'Pure Veg Thali'],
      distanceKm: 1.4,
      address: 'P-13 Connaught Circus, New Delhi',
      openingHours: '08:00-23:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 23:00' },
      vegetarian: true,
      vegan: true,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'no',
      phone: '+91 11 2331 7755',
      website: 'https://saravanabhavan.com',
      rating: 4.6,
      avgCost: 550,
      imageUrl: '/dining/south-indian-3.jpg',
      image: '/dining/south-indian-3.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'del-fb-3',
      name: 'Wenger’s Deli & Bakery',
      type: 'cafe',
      cuisine: ['Bakery', 'Panini', 'Shakes', 'Pastries'],
      distanceKm: 1.6,
      address: 'A-16 Connaught Place, New Delhi',
      openingHours: '11:00-20:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 20:00' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 11 4150 1444',
      website: null,
      rating: 4.7,
      avgCost: 600,
      imageUrl: '/dining/bakery-2.jpg',
      image: '/dining/bakery-2.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'del-fb-4',
      name: 'Midnight Express Diner',
      type: 'fast_food',
      cuisine: ['Rolls', 'Burgers', 'Late Night Shakes', 'Fast Food'],
      distanceKm: 1.1,
      address: 'Outer Circle, Connaught Place, New Delhi',
      openingHours: '24/7',
      openStatus: { isOpen: true, statusText: 'Open 24/7' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'yes',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 11 4355 2211',
      website: null,
      rating: 4.2,
      avgCost: 400,
      imageUrl: '/dining/fast-food-2.jpg',
      image: '/dining/fast-food-2.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'del-fb-5',
      name: 'Gulati Restaurant Pandara Road',
      type: 'restaurant',
      cuisine: ['Butter Chicken', 'Dal Makhani', 'North Indian', 'Tandoor'],
      distanceKm: 2.8,
      address: '6 Pandara Road Market, New Delhi',
      openingHours: '12:00-00:00',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 00:00' },
      vegetarian: false,
      vegan: false,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'wifi',
      phone: '+91 11 2338 8836',
      website: 'https://gulatirestaurant.com',
      rating: 4.8,
      avgCost: 1600,
      imageUrl: '/dining/indian.jpg',
      image: '/dining/indian.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    },
    {
      id: 'del-fb-6',
      name: 'Haldiram’s Chandni Chowk',
      type: 'restaurant',
      cuisine: ['Pure Veg Thali', 'Chaat', 'Chole Bhature', 'Indian Sweets'],
      distanceKm: 0.9,
      address: '1454/2 Chandni Chowk, Old Delhi',
      openingHours: '09:00-22:30',
      openStatus: { isOpen: true, statusText: 'Open Now · Closes 22:30' },
      vegetarian: true,
      vegan: true,
      takeaway: 'yes',
      delivery: 'yes',
      outdoorSeating: 'no',
      wheelchair: 'yes',
      internetAccess: 'no',
      phone: '+91 11 4756 6666',
      website: 'https://haldirams.com',
      rating: 4.5,
      avgCost: 450,
      imageUrl: '/dining/vegetarian-2.jpg',
      image: '/dining/vegetarian-2.jpg',
      imageSource: 'local',
      imageAttribution: 'TripResQ Curated'
    }
  ]
};

/**
 * Returns 5-6 deterministic fallback restaurant cards for any city or destination.
 * Case-insensitive lookup; falls back to Pune if not explicitly matched.
 *
 * @param {string} destination - City or destination name
 * @returns {Array<Object>} List of 6 normalized restaurant objects
 */
export function getFallbackRestaurants(destination = 'Pune') {
  if (!destination || typeof destination !== 'string') {
    return FALLBACK_RESTAURANTS.pune;
  }

  const clean = destination.trim().toLowerCase();

  if (clean.includes('goa') || clean.includes('madgaon') || clean.includes('panaji') || clean.includes('vasco')) {
    return FALLBACK_RESTAURANTS.goa;
  }

  if (clean.includes('mumbai') || clean.includes('bombay') || clean.includes('bandra') || clean.includes('dadar')) {
    return FALLBACK_RESTAURANTS.mumbai;
  }

  if (clean.includes('delhi') || clean.includes('ncr') || clean.includes('new delhi')) {
    return FALLBACK_RESTAURANTS.delhi;
  }

  if (clean.includes('pune') || clean.includes('shivajinagar') || clean.includes('deccan')) {
    return FALLBACK_RESTAURANTS.pune;
  }

  // Generic fallback: return Pune selection with custom location tag
  return FALLBACK_RESTAURANTS.pune;
}

export default getFallbackRestaurants;
